language: node_js
node_js:
  - 10 # use nodejs v10 LTS
cache: npm
branches:
  only:
    - develop # build develop instead of master
script:
  - hexo generate # generate static files
deploy:
  provider: pages
  skip_cleanup: true
  token: $GH_TOKEN
  keep_history: true
  on:
    all_branches: true # solve a permission problem
  target_branch: master
  local-dir: public